import 'package:local/dal/remote/engine_client.dart';
import 'package:local/domain/models/parcel.dart';

/// Pure domain service for farm parcel operations.
class ParcelService {
  final EngineClient _client;

  ParcelService({EngineClient? client}) : _client = client ?? EngineClient();

  Future<List<FarmParcel>> fetchParcels() => _client.getParcels();

  Future<FarmParcel?> createParcel({
    required String name,
    required double areaHectares,
    required double latitude,
    required double longitude,
    required String riceEcosystem,
    required String riceVariety,
    required DateTime sowingDate,
  }) {
    final parcel = FarmParcel(
      id: '', // Generated by backend
      name: name,
      areaHectares: areaHectares,
      latitude: latitude,
      longitude: longitude,
      riceEcosystem: riceEcosystem,
      riceVariety: riceVariety,
      sowingDate: sowingDate,
    );
    return _client.createParcel(parcel);
  }

  Future<FarmParcel?> updateParcel(FarmParcel parcel) => _client.updateParcel(parcel);

  Future<bool> deleteParcel(String id) => _client.deleteParcel(id);
}
