name: cloud
description: "Oryza-Elo Cloud Portal & Botanical Scientific Landing Page"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  oryzaelo_ui:
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/student/
    - assets/icons3d/
    - assets/plants/
    - assets/blueprint/
    - assets/img/
